events = {
  {
    id=1,
    text="Rebels are stirring in our west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=2,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=5,
    text="Bandits roam many roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=13,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=3,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=6,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=8,
    text="Bandits roam this roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=16,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=4,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=7,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=12,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=20,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=10,
    text="Rebels are stirring in our west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=9,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=23,
    text="Bandits roam those roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=22,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=11,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=14,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=32,
    text="Bandits roam this roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=27,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=21,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=15,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=34,
    text="Bandits roam this roads.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=29,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=26,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=17,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=39,
    text="Bandits roam this roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=31,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=30,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=18,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=46,
    text="Bandits roam our roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=36,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=33,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=19,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=60,
    text="Bandits roam our roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=38,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=35,
    text="Rebels are stirring in many west.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=24,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=64,
    text="Bandits roam this roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=41,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=44,
    text="Rebels are stirring in our west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=25,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=66,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=43,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=48,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=28,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=71,
    text="Bandits roam those roads.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=45,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=49,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=37,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=72,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=47,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=52,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=40,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=77,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=50,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=53,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=42,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=78,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=57,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=54,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=51,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=84,
    text="Bandits roam many roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=59,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=56,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=55,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=85,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=63,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=58,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=62,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=86,
    text="Bandits roam many roads.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=67,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=61,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=65,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=89,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
}
