events = {
  {
    id=1,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=2,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=3,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=4,
    text="Bandits roam those roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=5,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=6,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=7,
    text="Bandits roam our roads.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=8,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=9,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=10,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=11,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=12,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=13,
    text="Bandits roam our roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=14,
    text="Bandits roam those roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=15,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=16,
    text="Rebels are stirring in many west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=17,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=18,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=19,
    text="Rebels are stirring in our west.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=20,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=21,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=22,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=23,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=24,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=25,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=26,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=27,
    text="Bandits roam those roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=28,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=29,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=30,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=31,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=32,
    text="Rebels are stirring in many west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=33,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=34,
    text="Rebels are stirring in those west.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=35,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=36,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=37,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=38,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=39,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=40,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=41,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=42,
    text="Bandits roam many roads.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=43,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=44,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=45,
    text="Bandits roam those roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=46,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=47,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=48,
    text="Bandits roam those roads.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=49,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=50,
    text="Rebels are stirring in our west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=51,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=52,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=53,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=54,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=55,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=56,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=57,
    text="Rebels are stirring in many west.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=58,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=59,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=60,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=61,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=62,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=63,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=64,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=65,
    text="Bandits roam those roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=66,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=67,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=68,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=69,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=70,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=71,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=72,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=73,
    text="Bandits roam many roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=74,
    text="Bandits roam this roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=75,
    text="Rebels are stirring in this west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=76,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=77,
    text="Bandits roam many roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=78,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=79,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=80,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=81,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=82,
    text="Bandits roam our roads.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=83,
    text="Bandits roam our roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=84,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=85,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=86,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=87,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=88,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=89,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=90,
    text="Rebels are stirring in our west.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=91,
    text="Rebels are stirring in many west.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=92,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=93,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=94,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=95,
    text="Bandits roam our roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=96,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=97,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=98,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=99,
    text="Bandits roam those roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=100,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=101,
    text="Rebels are stirring in those west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=102,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=103,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=104,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=105,
    text="Bandits roam our roads.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=106,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=107,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=108,
    text="Bandits roam this roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=109,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=110,
    text="Bandits roam many roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=111,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=112,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=113,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=114,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=115,
    text="Rebels are stirring in many west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=116,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=117,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=118,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=119,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=120,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=121,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=122,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=123,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=124,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=125,
    text="Bandits roam many roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=126,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=127,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=128,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=129,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=130,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=131,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=132,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=133,
    text="Rebels are stirring in our west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=134,
    text="Rebels are stirring in those west.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=135,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=136,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=137,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=138,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=139,
    text="Bandits roam those roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=140,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=141,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=142,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=143,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "The gods will it.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=144,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=145,
    text="Rebels are stirring in many west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=146,
    text="Bandits roam this roads.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=147,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=148,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=149,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=150,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=151,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=152,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=153,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=154,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=155,
    text="Bandits roam our roads.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=156,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=157,
    text="Rebels are stirring in many west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=158,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=159,
    text="Bandits roam those roads.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=160,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=161,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=162,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=163,
    text="The harvest was poor this year.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=164,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=165,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=166,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=167,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=168,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=169,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=170,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=171,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=172,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=173,
    text="Rebels are stirring in those west.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=174,
    text="Rebels are stirring in many west.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The people grow restless.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=175,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=176,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=177,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=178,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=179,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=180,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=181,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=182,
    text="Bandits roam this roads.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=183,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=184,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "Money talks, sire.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=185,
    text="The harvest was poor this year.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=186,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=187,
    text="Bandits roam many roads.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Increase patrols.",
    effect_a={0,2,-1},
    opt_b="Hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=188,
    text="The harvest was poor this year.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "What could go wrong?",
    },
    opt_a="Distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="Do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=189,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=190,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=191,
    text="Rebels are stirring in those west.",
    counsel={
      "Think before acting.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The people grow restless.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=192,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "We must act swiftly!",
      "Let us pray on this.",
      "The people grow restless.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=193,
    text="Rebels are stirring in this west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The people grow restless.",
      "Money talks, sire.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=194,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "We must act swiftly!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=195,
    text="Rebels are stirring in this west.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "The gods will it.",
      "Whispers fill the halls.",
      "The markets shift in our favor.",
      "Hehehe... or not?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=196,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Let logic guide you.",
      "Prepare for battle!",
      "Faith shows the path.",
      "The common folk are uneasy.",
      "The markets shift in our favor.",
      "Flip a coin, maybe?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=197,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Think before acting.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "We can profit from this.",
      "What could go wrong?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=198,
    text="A nearby kingdom proposes alliance.",
    counsel={
      "Wisdom is our strength.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Hehehe... or not?",
    },
    opt_a="Accept alliance.",
    effect_a={1,1,-2},
    opt_b="Decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=199,
    text="Rebels are stirring in our west.",
    counsel={
      "Wisdom is our strength.",
      "Prepare for battle!",
      "Let us pray on this.",
      "Whispers fill the halls.",
      "Money talks, sire.",
      "What could go wrong?",
    },
    opt_a="Send troops.",
    effect_a={0,2,-1},
    opt_b="Offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=200,
    text="A mysterious traveler offers a relic.",
    counsel={
      "Let logic guide you.",
      "Strike while the iron is hot!",
      "Let us pray on this.",
      "The common folk are uneasy.",
      "We can profit from this.",
      "Flip a coin, maybe?",
    },
    opt_a="Buy the relic.",
    effect_a={-2,0,1},
    opt_b="Refuse the deal.",
    effect_b={1,0,-1},
  },
}
