events = {
  {
    id=1,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "whispers fill the halls.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=2,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=5,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "faith shows the path.",
      "the people grow restless.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=13,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "the gods will it.",
      "the people grow restless.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=3,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=6,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=8,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=16,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "the gods will it.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=4,
    text="rebels rising in the west",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=7,
    text="traveler brings rare relic",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=12,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "the gods will it.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=20,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "the gods will it.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=10,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=9,
    text="traveler brings rare relic",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "the gods will it.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=23,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=22,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=11,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=14,
    text="traveler brings rare relic",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=32,
    text="bandits block many roads",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "faith shows the path.",
      "whispers fill the halls.",
      "money talks, sire.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=27,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "the gods will it.",
      "whispers fill the halls.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=21,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "the gods will it.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=15,
    text="neighbor kingdom wants pact",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=34,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "faith shows the path.",
      "whispers fill the halls.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=29,
    text="this year's harvest was poor",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=26,
    text="rebels rising in the west",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=17,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "the gods will it.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=39,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=31,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=30,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=18,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=46,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=36,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "the gods will it.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=33,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "whispers fill the halls.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=19,
    text="neighbor kingdom wants pact",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=60,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "the gods will it.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=38,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=35,
    text="rebels rising in the west",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "let us pray on this.",
      "the people grow restless.",
      "money talks, sire.",
      "flip a coin, maybe?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=24,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=64,
    text="bandits block many roads",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=41,
    text="this year's harvest was poor",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "the gods will it.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=44,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=25,
    text="neighbor kingdom wants pact",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "faith shows the path.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=66,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "let us pray on this.",
      "whispers fill the halls.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=43,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=48,
    text="rebels rising in the west",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "the gods will it.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=28,
    text="traveler brings rare relic",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=71,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=45,
    text="this year's harvest was poor",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "the gods will it.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=49,
    text="rebels rising in the west",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "the gods will it.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=37,
    text="traveler brings rare relic",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=72,
    text="bandits block many roads",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "faith shows the path.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=47,
    text="this year's harvest was poor",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=52,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "the gods will it.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=40,
    text="neighbor kingdom wants pact",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "faith shows the path.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=77,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "the gods will it.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=50,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "let us pray on this.",
      "whispers fill the halls.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=53,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=42,
    text="traveler brings rare relic",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "faith shows the path.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=78,
    text="bandits block many roads",
    counsel={
      "think before acting.",
      "prepare for battle!",
      "let us pray on this.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=57,
    text="this year's harvest was poor",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "the gods will it.",
      "whispers fill the halls.",
      "the markets shift in our favor.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=54,
    text="rebels rising in the west",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "faith shows the path.",
      "the people grow restless.",
      "the markets shift in our favor.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=51,
    text="neighbor kingdom wants pact",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "the gods will it.",
      "whispers fill the halls.",
      "money talks, sire.",
      "hehehe... or not?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=84,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=59,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "let us pray on this.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=56,
    text="rebels rising in the west",
    counsel={
      "let logic guide you.",
      "strike while the iron is hot!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=55,
    text="neighbor kingdom wants pact",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=85,
    text="bandits block many roads",
    counsel={
      "think before acting.",
      "we must act swiftly!",
      "the gods will it.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=63,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "the gods will it.",
      "whispers fill the halls.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=58,
    text="rebels rising in the west",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "the gods will it.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=62,
    text="traveler brings rare relic",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "the gods will it.",
      "whispers fill the halls.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="buy the relic.",
    effect_a={-2,0,1},
    opt_b="refuse the deal.",
    effect_b={1,0,-1},
  },
  {
    id=86,
    text="bandits block many roads",
    counsel={
      "let logic guide you.",
      "we must act swiftly!",
      "faith shows the path.",
      "the people grow restless.",
      "we can profit from this.",
      "hehehe... or not?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
  {
    id=67,
    text="this year's harvest was poor",
    counsel={
      "let logic guide you.",
      "prepare for battle!",
      "faith shows the path.",
      "whispers fill the halls.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="distribute royal grain.",
    effect_a={2,-1,0},
    opt_b="do nothing.",
    effect_b={-2,1,0},
  },
  {
    id=61,
    text="rebels rising in the west",
    counsel={
      "wisdom is our strength.",
      "we must act swiftly!",
      "faith shows the path.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "what could go wrong?",
    },
    opt_a="send troops.",
    effect_a={0,2,-1},
    opt_b="offer peace.",
    effect_b={1,-2,1},
  },
  {
    id=65,
    text="neighbor kingdom wants pact",
    counsel={
      "wisdom is our strength.",
      "strike while the iron is hot!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "money talks, sire.",
      "what could go wrong?",
    },
    opt_a="accept alliance.",
    effect_a={1,1,-2},
    opt_b="decline it.",
    effect_b={-1,-1,2},
  },
  {
    id=89,
    text="bandits block many roads",
    counsel={
      "wisdom is our strength.",
      "prepare for battle!",
      "let us pray on this.",
      "the common folk are uneasy.",
      "we can profit from this.",
      "flip a coin, maybe?",
    },
    opt_a="increase patrols.",
    effect_a={0,2,-1},
    opt_b="hire mercenaries.",
    effect_b={-1,1,1},
  },
}
